-- Content Wave 1: long, original, bilingual story + review for marquee titles.
SET NAMES utf8mb4;

UPDATE movies SET overview =
'Story / कहानी:\n\nSet in the devastating aftermath of Avengers: Infinity War, Endgame opens on a universe in mourning. Thanos has used the six Infinity Stones to erase half of all living beings with a single snap, and the heroes who once seemed unstoppable are left broken, scattered and haunted by failure. Five years pass. Grief has hardened into routine — until Scott Lang escapes the Quantum Realm with a wild idea that reignites hope: time itself might be the key to undoing the snap.\n\nWhat follows is an audacious "time heist". The surviving Avengers — Iron Man, Captain America, Thor, Black Widow, Hulk, Hawkeye, Nebula, Rocket and Ant-Man — split across different moments in their own history to retrieve the Stones before Thanos ever found them. Each journey forces a hero to face their past: old loves, dead parents, former selves and the choices that shaped them. The mission is not just about power; it is about closure, redemption and what these heroes are willing to sacrifice.\n\nThe film builds to one of the most staggering battles ever put on screen, as every hero of this universe stands together for a final, desperate stand. Endgame is the emotional culmination of more than twenty interconnected films — a story about loss, legacy and the price of victory. It rewards a decade of investment with goodbyes that land like thunder, proving that the greatest heroes are defined not by their strength, but by what they give up.\n\nयह कहानी इन्फिनिटी वॉर की विनाशकारी हार के बाद शुरू होती है, जहाँ थानोस ने छह इन्फिनिटी स्टोन्स से ब्रह्मांड के आधे जीवों को मिटा दिया है। पाँच साल बाद, स्कॉट लैंग क्वांटम रियल्म से लौटकर एक उम्मीद जगाता है — समय में पीछे जाकर सब कुछ ठीक किया जा सकता है। बचे हुए एवेंजर्स एक खतरनाक "टाइम हाइस्ट" पर निकलते हैं, जहाँ हर नायक को अपने अतीत, अपने खोए हुए लोगों और अपनी गलतियों का सामना करना पड़ता है। फिल्म एक विशाल आखिरी जंग की ओर बढ़ती है, जहाँ बलिदान, वफ़ादारी और वीरता की आखिरी परीक्षा होती है। बाईस फिल्मों की इस गाथा का यह भावुक चरम बिंदु साबित करता है कि सबसे बड़े नायक अपनी ताकत से नहीं, बल्कि अपने त्याग से पहचाने जाते हैं।'
WHERE slug='avengers-endgame';

UPDATE movies SET overview =
'Story / कहानी:\n\nPathaan follows an exiled Indian intelligence officer who has spent years operating in the shadows, presumed broken after a mission gone wrong. When a rogue paramilitary outfit called Outfit X, led by a vengeful former agent named Jim, threatens India with a devastating biological attack, Pathaan is pulled back into the fight. What begins as a routine recovery operation spirals into a globe-spanning chase across snowbound peaks, glittering cities and the open sea.\n\nAt its heart, the film is about loyalty — to country, to comrades, and to a code that survives even betrayal. Pathaan is joined by Rubai, an agent with her own hidden agenda, and the two circle each other in a dance of trust and suspicion. Jim, once a patriot himself, has been hollowed out by personal loss and now believes the system that abandoned him deserves to burn. The clash between the two men becomes a battle of ideologies as much as fists and bullets.\n\nPacked with breathtaking action set-pieces, sleek style and an undercurrent of emotion, Pathaan marked a triumphant, large-scale return for its leading star and reignited the Indian spy-thriller genre. It is a film about second chances — about a soldier the country wrote off, who answers the call one more time when no one else can. Beneath the spectacle lies a simple, stirring idea: that some people will give everything to protect a nation that once turned its back on them.\n\nपठान एक निर्वासित भारतीय खुफिया अधिकारी की कहानी है, जो एक बिगड़े मिशन के बाद सालों से छाया में जी रहा है। जब जिम नाम के एक बदला लेने वाले पूर्व एजेंट के नेतृत्व वाली एक बाग़ी निजी सेना भारत पर एक खतरनाक जैविक हमले की धमकी देती है, तो पठान फिर से मैदान में लौटता है। बर्फ़ीली चोटियों, चमचमाते शहरों और खुले समंदर तक फैले इस रोमांच में, पठान का साथ देती है रुबाई, जिसके अपने छिपे मकसद हैं। यह फिल्म वफ़ादारी, दूसरे मौके और उस सिपाही की कहानी है जिसे देश ने भुला दिया था, पर वह एक बार फिर पुकार का जवाब देता है। शानदार एक्शन और भावनाओं से भरी यह फिल्म भारतीय जासूसी सिनेमा की दमदार वापसी है।'
WHERE slug='pathaan';

UPDATE movies SET overview =
'Story / कहानी:\n\nJawan tells two interlocking stories separated by decades. In the present, a mysterious, charismatic man leads a band of fearless women on a series of daring, theatrical missions — hijacking a metro, confronting corrupt tycoons and forcing the powerful to answer for the suffering of ordinary people. He is part Robin Hood, part avenging spirit, and entirely a man on a mission. In the past, a heroic soldier named Vikram Rathore is betrayed and destroyed by the very greed his "son" now fights against.\n\nThe film weaves a deeply emotional thread of fathers and sons, sacrifice and justice, through its high-voltage action. Each of the women in Jawan''s crew carries her own wound — a story of injustice that the system ignored — and together they become a force that the corrupt cannot silence. Standing against them is Kaali, a ruthless arms dealer whose empire is built on the bodies of the innocent.\n\nMore than a revenge thriller, Jawan is a rallying cry. Between its explosive chases and crowd-igniting moments, the film pauses to speak directly about accountability — about farmers, healthcare, and the duty of citizens to demand better from those in power. It is a massive, emotionally charged spectacle that blends mainstream entertainment with a social conscience, anchored by a double role of remarkable range. The result is a film that thrills the senses while asking its audience a pointed question: who really holds the power, and who pays the price?\n\nजवान दो कहानियाँ बुनती है, जो दशकों के फासले से जुड़ी हैं। वर्तमान में, एक रहस्यमयी और करिश्माई आदमी निडर महिलाओं की एक टोली का नेतृत्व करता है, जो भ्रष्ट ताकतवर लोगों को आम जनता के दुख का हिसाब देने पर मजबूर करते हैं। अतीत में, विक्रम राठौड़ नाम का एक वीर सिपाही उसी लालच का शिकार होता है जिसके खिलाफ उसका "बेटा" अब लड़ रहा है। पिता-पुत्र, बलिदान और न्याय की भावुक डोर से बुनी यह फिल्म, धमाकेदार एक्शन के बीच किसान, स्वास्थ्य और जवाबदेही जैसे मुद्दों पर सीधी बात करती है। मनोरंजन और सामाजिक चेतना का मेल, और शाहरुख खान का दमदार दोहरा किरदार — जवान एक विशाल, भावुक सिनेमाई अनुभव है।'
WHERE slug='jawan';

UPDATE movies SET overview =
'Story / कहानी:\n\nThree engineering students — Rancho, Farhan and Raju — meet on their first day at one of India''s most prestigious and pressure-cooker colleges, where the cruel principal, "Virus", treats marks as the only measure of a human being. Rancho is unlike anyone they have ever met: brilliant, fearless and gloriously indifferent to the rat race. He chases knowledge for the joy of it, not for grades, and his philosophy — "Aal izz well" — slowly transforms the lives of his two friends and everyone around him.\n\nTold across two timelines, the film follows Farhan and Raju years later as they set off on a road trip to find their long-lost friend who vanished after graduation. Their search peels back the mystery of who Rancho really was, while flashbacks reveal the heartbreak, comedy and quiet rebellion of their college years. Along the way the film tackles the crushing weight of parental expectation, the tragedy of students broken by an unforgiving system, and the courage it takes to follow your own passion.\n\n3 Idiots became a cultural phenomenon because it wrapped a serious message — that education should spark curiosity, not fear — inside warmth, laughter and unforgettable characters. It is a story about friendship that outlasts distance, about chasing excellence rather than success, and about the simple wisdom that if you do what you love, success will follow on its own. Funny, moving and endlessly quotable, it remains one of the most beloved films in Indian cinema.\n\nतीन इंजीनियरिंग छात्र — रैंचो, फरहान और राजू — भारत के एक सबसे प्रतिष्ठित और दबाव भरे कॉलेज में मिलते हैं, जहाँ कठोर प्रिंसिपल "वायरस" के लिए नंबर ही इंसान की एकमात्र पहचान हैं। रैंचो सबसे अलग है — होनहार, निडर और रेस की दौड़ से बेपरवाह। उसका फ़लसफ़ा "ऑल इज़ वेल" धीरे-धीरे उसके दोस्तों की ज़िंदगी बदल देता है। दो समयरेखाओं में बुनी यह कहानी, सालों बाद अपने खोए दोस्त को ढूँढने निकले फरहान और राजू के साथ चलती है। माता-पिता की उम्मीदों का बोझ, टूटते छात्र और अपने जुनून को चुनने का साहस — 3 इडियट्स हँसी, भावना और गहरे संदेश के साथ दोस्ती और सच्ची शिक्षा की एक अविस्मरणीय कहानी है।'
WHERE slug='3-idiots';

UPDATE movies SET overview =
'Story / कहानी:\n\nIn the rocky, sun-scorched village of Ramgarh, a retired police officer named Thakur hires two small-time crooks, Jai and Veeru, for a deeply personal mission: to capture the savage bandit Gabbar Singh, who once butchered the Thakur''s entire family and left him broken. The two petty thieves — loyal to each other above all else — arrive expecting easy money, but Ramgarh slowly works its way into their hearts through its people, its quiet courage and the two women who change them.\n\nWhat unfolds is a sweeping tale of friendship, vengeance and sacrifice. Gabbar Singh is no ordinary villain; he is a force of pure menace whose laughter echoes terror across the valley. As Jai and Veeru are drawn deeper into the village''s fight for survival, their carefree bravado hardens into genuine heroism, and the bond between the two friends is tested to its breaking point.\n\nSholay is the definitive Indian epic — a "curry western" that fused action, comedy, romance, music and tragedy into a single unforgettable whole. Its characters and dialogues became part of the cultural fabric of a nation, quoted by generations who know every beat by heart. Beneath the spectacle beats a timeless story about ordinary men who rise to extraordinary courage, about loyalty that demands the ultimate price, and about good standing firm against cruelty. Decades on, it remains the towering benchmark against which Indian blockbusters are still measured.\n\nरामगढ़ के पथरीले गाँव में, रिटायर पुलिस अफसर ठाकुर दो छोटे-मोटे चोरों, जय और वीरू को एक निजी मिशन के लिए बुलाता है: खूँखार डाकू गब्बर सिंह को पकड़ना, जिसने कभी ठाकुर के पूरे परिवार को मार डाला था। दोस्ती में अटूट ये दोनों आसान पैसे की उम्मीद में आते हैं, पर रामगढ़ के लोग और दो औरतें उन्हें बदल देती हैं। गब्बर कोई आम खलनायक नहीं — उसकी हँसी पूरी घाटी में दहशत फैलाती है। दोस्ती, बदले और बलिदान की यह भव्य गाथा, एक्शन, कॉमेडी, रोमांस और त्रासदी का अनोखा मेल है। शोले भारतीय सिनेमा की वह मिसाल है जिसके किरदार और संवाद आज भी हर पीढ़ी की ज़ुबान पर हैं।'
WHERE slug='sholay';

UPDATE movies SET overview =
'Story / कहानी:\n\nGangs of Wasseypur Part 1 is a sprawling crime saga that traces a blood feud across generations in the coal-mining badlands of Dhanbad. It begins in pre-independence India, where Shahid Khan is exiled after impersonating a notorious dacoit, and his clash with the ruthless businessman Ramadhir Singh plants the seed of a vendetta that will consume their families for decades. When Shahid is killed, his son Sardar Khan grows up with a single vow shaved into his very being: revenge.\n\nSardar becomes a force of nature — a fearless, swaggering outlaw who carves out power through coal, scrap, butchery and sheer audacity, all while the patient, calculating Ramadhir Singh tightens his grip on politics and industry. The film charts Sardar''s rise and the violence that follows him home, weaving in his volatile marriages, his sons, and a world where loyalty is currency and betrayal is inevitable.\n\nRaw, darkly funny and soaked in the texture of small-town India, Gangs of Wasseypur is less a conventional gangster film than an epic about power, ego and the way hatred is inherited like a family heirloom. Its earthy dialogue, unforgettable characters and pulsing soundtrack made it a modern cult classic. Part 1 lays the foundation of the feud and ends on a gut-punch that propels everything into its explosive second half — a portrait of men who would rather die ruling than live in peace.\n\nगैंग्स ऑफ वासेपुर पार्ट 1 धनबाद की कोयला-खदानों की दुनिया में पीढ़ियों तक चलने वाली एक खूनी दुश्मनी की गाथा है। आज़ादी से पहले शाहिद खान को निर्वासित किया जाता है, और बेरहम कारोबारी रामाधीर सिंह से उसकी टक्कर एक ऐसी दुश्मनी की नींव रखती है जो दशकों तक दोनों परिवारों को निगल जाती है। शाहिद की मौत के बाद उसका बेटा सरदार खान सिर्फ एक कसम के साथ बड़ा होता है: बदला। सरदार एक निडर, दबंग बागी बन जाता है, जबकि रामाधीर सिंह राजनीति और उद्योग पर अपनी पकड़ मज़बूत करता रहता है। कच्ची, डार्क ह्यूमर से भरी और छोटे शहर की मिट्टी में रची यह फिल्म ताकत, अहंकार और विरासत में मिली नफ़रत की एक आधुनिक कल्ट क्लासिक है।'
WHERE slug='gangs-of-wasseypur-part-1';

UPDATE movies SET overview =
'Story / कहानी:\n\nVijay Salgaonkar is an ordinary, fourth-grade dropout who runs a small cable TV business in a sleepy Goan town. He is a devoted husband and father, a self-made man whose only education comes from the countless films he watches late into the night. His simple, contented life is shattered in a single terrible moment when his family becomes entangled in the accidental death of a boy — the privileged, predatory son of a powerful Inspector General of Police.\n\nTo protect the people he loves, Vijay does something extraordinary: armed with nothing but cunning and everything he has absorbed from the movies, he constructs an elaborate, watertight web of false alibis and misdirection. What follows is a tense, brilliant cat-and-mouse game as a relentless mother — and top cop — refuses to believe his story and tears his life apart searching for the truth. Every interrogation, every search, becomes a battle of wits between a desperate father and the full force of the law.\n\nDrishyam is a masterclass in suspense built not on action but on intelligence, ordinary love and the lengths a man will go to for his family. It asks uncomfortable questions about justice, guilt and morality, and keeps audiences guessing until its final, jaw-dropping revelation. A remake that became a phenomenon in its own right, it proved that the most gripping thriller can be spun from an everyman with nothing but his wits and an unbreakable will to protect his own.\n\nविजय साल्गांवकर एक आम, चौथी पास आदमी है, जो गोवा के एक छोटे शहर में केबल टीवी का कारोबार चलाता है। फिल्मों का दीवाना यह समर्पित पति और पिता, एक भयानक पल में तब हिल जाता है जब उसका परिवार एक ताकतवर पुलिस अफसर के बिगड़ैल बेटे की हादसाती मौत में फँस जाता है। अपने परिवार को बचाने के लिए विजय सिर्फ अपनी चालाकी और फिल्मों से सीखी समझ के दम पर झूठे सबूतों और अलीबाई का एक मज़बूत जाल बुनता है। फिर शुरू होता है एक तनावपूर्ण बिल्ली-चूहे का खेल, जहाँ एक माँ और टॉप पुलिस अफसर सच ढूँढने उसकी ज़िंदगी उधेड़ देती है। दृश्यम बुद्धि, परिवार के प्यार और सस्पेंस की एक बेजोड़ मिसाल है।'
WHERE slug='drishyam-2015';

UPDATE movies SET overview =
'Story / कहानी:\n\nWalter White is a brilliant but quietly defeated high-school chemistry teacher in Albuquerque, scraping by to support his pregnant wife and disabled son. On his fiftieth birthday he is handed a death sentence: terminal lung cancer. Facing his own mortality and the terror of leaving his family with nothing, the mild-mannered everyman makes a fateful choice — to use his genius for chemistry to "cook" crystal meth, partnering with a washed-out former student named Jesse Pinkman.\n\nWhat begins as a desperate bid to secure his family''s future becomes the slow, mesmerising transformation of a good man into something monstrous. As Walter adopts the alias "Heisenberg", his empire grows and so does his appetite for power, pride and control. The series charts every step of his descent through a gallery of unforgettable figures — a brother-in-law in the DEA, a chillingly polite drug kingpin, a sleazy criminal lawyer — and the relationships that fracture under the weight of his lies.\n\nWidely regarded as one of the greatest television dramas ever made, Breaking Bad is a tragedy in the classic sense: a story about choices, consequences and the lies we tell ourselves. It asks how far a person will go when they finally stop being afraid, and whether the people we love can survive who we truly become. Across five seasons of relentless tension, dark humour and shattering moral reckoning, it builds to one of the most satisfying conclusions in TV history.\n\nवॉल्टर व्हाइट अल्बुकर्की का एक होनहार मगर हारा हुआ हाई-स्कूल केमिस्ट्री टीचर है, जो अपने परिवार का पेट पालने के लिए जूझता है। पचासवें जन्मदिन पर उसे लाइलाज फेफड़ों के कैंसर का पता चलता है। अपने परिवार को कुछ न दे पाने के डर से, यह सीधा-सादा आदमी अपनी केमिस्ट्री की प्रतिभा से ड्रग्स "कुक" करने लगता है, अपने पूर्व छात्र जेसी पिंकमैन के साथ। जो एक बेताब फैसले से शुरू होता है, वह एक अच्छे इंसान के एक राक्षस में बदलने की धीमी, सम्मोहक कहानी बन जाता है। "हाइज़ेनबर्ग" बनते ही उसकी ताकत और घमंड की भूख बढ़ती जाती है। पाँच सीज़न में फैली यह सीरीज़ फैसलों, अंजामों और खुद से बोले झूठ की एक क्लासिक त्रासदी है — टेलीविज़न इतिहास की सबसे बेहतरीन कृतियों में से एक।'
WHERE slug='breaking-bad';
