-- ============================================================
--  TopHDMovies — append हिंदी to the 37 MCU films' overviews.
--  Apply to LOCAL DB ONCE, then push live with sync-tmdb.
--  (CONCAT appends — do not run twice or Hindi will duplicate.)
-- ============================================================
SET NAMES utf8mb4;

UPDATE movies SET overview = CONCAT(overview,'\n\n','अरबपति आविष्कारक टोनी स्टार्क बंदी बनाए जाने के बाद एक शक्तिशाली कवच बनाकर भागता है और आयरन मैन बन जाता है। यह दमदार ओरिजिन कहानी पूरी मार्वल दुनिया की नींव रखती है।'), short_description = CONCAT(short_description,' | ','टोनी स्टार्क एक हाई-टेक कवच बनाकर आयरन मैन बन जाता है।') WHERE slug='iron-man';
UPDATE movies SET overview = CONCAT(overview,'\n\n','भगोड़ा वैज्ञानिक ब्रूस बैनर अपने भीतर छिपे राक्षस हल्क को काबू करने का इलाज ढूँढता है, तभी एक और खतरनाक ताकत सामने आ जाती है।'), short_description = CONCAT(short_description,' | ','ब्रूस बैनर हल्क पर काबू पाने की कोशिश करता है।') WHERE slug='the-incredible-hulk';
UPDATE movies SET overview = CONCAT(overview,'\n\n','अपनी पहचान सार्वजनिक होने के बाद टोनी स्टार्क को सरकार, प्रतिद्वंद्वियों और एक खतरनाक दुश्मन का सामना करना पड़ता है, जबकि उसे जिंदा रखने वाली तकनीक ही उसे धीरे-धीरे मार रही है।'), short_description = CONCAT(short_description,' | ','टोनी स्टार्क एक बदला लेने वाले दुश्मन से भिड़ता है।') WHERE slug='iron-man-2';
UPDATE movies SET overview = CONCAT(overview,'\n\n','घमंडी देवता थॉर को धरती पर निर्वासित कर दिया जाता है, जहाँ उसे विनम्रता सीखनी है, तभी उसका चालाक भाई लोकी सिंहासन हड़पने की साज़िश रचता है।'), short_description = CONCAT(short_description,' | ','थॉर को खुद को योग्य साबित करना है।') WHERE slug='thor';
UPDATE movies SET overview = CONCAT(overview,'\n\n','कमज़ोर मगर बहादुर युवक स्टीव रॉजर्स एक प्रयोग के ज़रिए सुपर-सोल्जर कैप्टन अमेरिका बन जाता है और दूसरे विश्व युद्ध में एक खतरनाक दुश्मन से लड़ता है।'), short_description = CONCAT(short_description,' | ','स्टीव रॉजर्स कैप्टन अमेरिका बनता है।') WHERE slug='captain-america-the-first-avenger';
UPDATE movies SET overview = CONCAT(overview,'\n\n','जब धरती पर बड़ा खतरा मंडराता है, तो दुनिया के सबसे शक्तिशाली नायक पहली बार एकजुट होकर एक एलियन सेना के खिलाफ मोर्चा संभालते हैं।'), short_description = CONCAT(short_description,' | ','सुपरहीरो पहली बार एकजुट होते हैं।') WHERE slug='the-avengers';
UPDATE movies SET overview = CONCAT(overview,'\n\n','अतीत के सदमे से जूझता टोनी स्टार्क एक रहस्यमयी आतंकवादी और खतरनाक तकनीक का सामना करता है और सिर्फ अपनी सूझबूझ के दम पर लड़ता है।'), short_description = CONCAT(short_description,' | ','टोनी स्टार्क एक रहस्यमयी आतंकी से भिड़ता है।') WHERE slug='iron-man-3';
UPDATE movies SET overview = CONCAT(overview,'\n\n','एक प्राचीन दुश्मन ब्रह्मांड को अंधकार में डुबोना चाहता है, और थॉर को अपने धोखेबाज़ भाई लोकी से हाथ मिलाकर सब कुछ बचाना है।'), short_description = CONCAT(short_description,' | ','थॉर और लोकी मिलकर ब्रह्मांड बचाते हैं।') WHERE slug='thor-the-dark-world';
UPDATE movies SET overview = CONCAT(overview,'\n\n','कैप्टन अमेरिका को अपनी ही संस्था के भीतर छिपी एक बड़ी साज़िश का पता चलता है और उसे अपने अतीत के एक खतरनाक हत्यारे का सामना करना पड़ता है।'), short_description = CONCAT(short_description,' | ','कैप्टन अमेरिका एक बड़ी साज़िश का पर्दाफ़ाश करता है।') WHERE slug='captain-america-the-winter-soldier';
UPDATE movies SET overview = CONCAT(overview,'\n\n','एक शरारती अंतरिक्ष लुटेरा और बेमेल बागियों की टोली एक शक्तिशाली चीज़ को बचाने के लिए एकजुट होकर पूरी आकाशगंगा को बचाने निकल पड़ती है।'), short_description = CONCAT(short_description,' | ','बेमेल नायकों की टोली आकाशगंगा बचाती है।') WHERE slug='guardians-of-the-galaxy';
UPDATE movies SET overview = CONCAT(overview,'\n\n','शांति के लिए बनाया गया एक प्रोग्राम जब खतरनाक रोबोट अल्ट्रॉन में बदल जाता है, तो एवेंजर्स को मानवता को विनाश से बचाने के लिए जूझना पड़ता है।'), short_description = CONCAT(short_description,' | ','एवेंजर्स अल्ट्रॉन से भिड़ते हैं।') WHERE slug='avengers-age-of-ultron';
UPDATE movies SET overview = CONCAT(overview,'\n\n','सुधरने की चाह रखने वाला चोर स्कॉट लैंग एक ऐसा सूट पहनता है जो उसे छोटा कर देता है पर ताकत बढ़ा देता है, और एक बड़ी डकैती से दुनिया बचाता है।'), short_description = CONCAT(short_description,' | ','स्कॉट लैंग एंट-मैन बनता है।') WHERE slug='ant-man';
UPDATE movies SET overview = CONCAT(overview,'\n\n','सरकारी नियंत्रण के सवाल पर एवेंजर्स दो गुटों में बँट जाते हैं — एक तरफ कैप्टन अमेरिका, दूसरी तरफ आयरन मैन। दोस्ती और भरोसा टूटने की कगार पर पहुँच जाते हैं।'), short_description = CONCAT(short_description,' | ','एवेंजर्स दो गुटों में बँट जाते हैं।') WHERE slug='captain-america-civil-war';
UPDATE movies SET overview = CONCAT(overview,'\n\n','एक हादसे के बाद घमंडी सर्जन स्टीफन स्ट्रेंज जादू की दुनिया में इलाज ढूँढता है और मिस्टिक आर्ट्स में महारत हासिल कर हकीकत की रक्षा करने लगता है।'), short_description = CONCAT(short_description,' | ','डॉक्टर स्ट्रेंज जादू की दुनिया में कदम रखता है।') WHERE slug='doctor-strange';
UPDATE movies SET overview = CONCAT(overview,'\n\n','गार्डियंस का बेमेल परिवार इस बार अपने अतीत के गहरे राज़ों का सामना करता है, जहाँ रिश्ते और वफ़ादारियाँ परखी जाती हैं।'), short_description = CONCAT(short_description,' | ','गार्डियंस अपने अतीत के राज़ खोलते हैं।') WHERE slug='guardians-of-the-galaxy-vol-2';
UPDATE movies SET overview = CONCAT(overview,'\n\n','खुद को साबित करने को बेताब किशोर पीटर पार्कर स्कूल और सुपरहीरो ज़िंदगी में संतुलन बिठाता है, तभी एक खतरनाक हथियार तस्कर उसके शहर को निशाना बनाता है।'), short_description = CONCAT(short_description,' | ','किशोर पीटर पार्कर स्पाइडर-मैन बनता है।') WHERE slug='spider-man-homecoming';
UPDATE movies SET overview = CONCAT(overview,'\n\n','अपने हथौड़े से वंचित और एक अनजान ग्रह पर फँसा थॉर अपनी आज़ादी के लिए लड़ता है और अपने राज्य को विनाश से बचाने की दौड़ में जुट जाता है।'), short_description = CONCAT(short_description,' | ','थॉर अपने राज्य को बचाने की दौड़ में।') WHERE slug='thor-ragnarok';
UPDATE movies SET overview = CONCAT(overview,'\n\n','अपने उन्नत और गुप्त देश का राजा बनने लौटा युवा नायक एक खतरनाक प्रतिद्वंद्वी से भिड़ता है जो सत्ता पर अपना हक जताता है।'), short_description = CONCAT(short_description,' | ','युवा राजा अपने उन्नत देश की रक्षा करता है।') WHERE slug='black-panther';
UPDATE movies SET overview = CONCAT(overview,'\n\n','एक क्रूर ब्रह्मांडीय खलनायक थानोस छह शक्तिशाली पत्थरों को इकट्ठा कर पूरी सृष्टि को बदलना चाहता है, और उसे रोकने के लिए सभी नायकों को एकजुट होना पड़ता है।'), short_description = CONCAT(short_description,' | ','नायक थानोस को रोकने के लिए एकजुट होते हैं।') WHERE slug='avengers-infinity-war';
UPDATE movies SET overview = CONCAT(overview,'\n\n','हीरो और पिता दोनों की ज़िम्मेदारी निभाते स्कॉट लैंग अपनी नई साथी वास्प के साथ अतीत के राज़ खोलने के मिशन पर निकलता है।'), short_description = CONCAT(short_description,' | ','एंट-मैन और वास्प एक नए मिशन पर।') WHERE slug='ant-man-and-the-wasp';
UPDATE movies SET overview = CONCAT(overview,'\n\n','दो एलियन दुनियों के बीच फँसी एक शक्तिशाली योद्धा धरती पर पहुँचती है और अपने भूले हुए अतीत के टुकड़ों को जोड़ते हुए अपनी असली ताकत पहचानती है।'), short_description = CONCAT(short_description,' | ','एक शक्तिशाली योद्धा अपनी असली ताकत पहचानती है।') WHERE slug='captain-marvel';
UPDATE movies SET overview = CONCAT(overview,'\n\n','एक विनाशकारी हार के बाद बचे हुए नायक खोई हुई दुनिया को वापस लाने की आखिरी और सबसे जोखिम भरी योजना के लिए एकजुट होते हैं। यह एक युग का भावुक अंत है।'), short_description = CONCAT(short_description,' | ','नायक सब कुछ वापस लाने की आखिरी कोशिश करते हैं।') WHERE slug='avengers-endgame';
UPDATE movies SET overview = CONCAT(overview,'\n\n','छुट्टियों पर यूरोप गया पीटर पार्कर खतरनाक एलिमेंटल ताकतों से लड़ने में उलझ जाता है, जहाँ हर चीज़ वैसी नहीं जैसी दिखती है।'), short_description = CONCAT(short_description,' | ','पीटर पार्कर यूरोप में नए खतरों से जूझता है।') WHERE slug='spider-man-far-from-home';
UPDATE movies SET overview = CONCAT(overview,'\n\n','अपने अतीत के खतरनाक राज़ों का सामना करती जासूस नताशा अपने बिछड़े नकली परिवार से दोबारा मिलती है, जबकि एक घातक संगठन उसके पीछे है।'), short_description = CONCAT(short_description,' | ','नताशा अपने अतीत का सामना करती है।') WHERE slug='black-widow';
UPDATE movies SET overview = CONCAT(overview,'\n\n','शांत ज़िंदगी जी रहा शांग-ची तब वापस खिंच आता है जब उसके पिता का रहस्यमयी संगठन उसे ढूँढ निकालता है, और उसे अपनी विरासत अपनानी पड़ती है।'), short_description = CONCAT(short_description,' | ','शांग-ची अपनी विरासत और किस्मत से जूझता है।') WHERE slug='shang-chi-and-the-legend-of-the-ten-rings';
UPDATE movies SET overview = CONCAT(overview,'\n\n','हज़ारों साल से चुपचाप मानवता की रक्षा कर रहे अमर नायक एक प्राचीन खतरे के लौटने पर सामने आते हैं और दुनिया को बचाने का फैसला करते हैं।'), short_description = CONCAT(short_description,' | ','अमर नायक एक प्राचीन खतरे से भिड़ते हैं।') WHERE slug='eternals';
UPDATE movies SET overview = CONCAT(overview,'\n\n','पहचान छिपाने का एक जादू बिगड़ जाता है और मल्टीवर्स से खतरनाक दुश्मन पीटर पार्कर की दुनिया में आ धमकते हैं, जहाँ उसे जीवन के सबसे कठिन फैसले लेने हैं।'), short_description = CONCAT(short_description,' | ','मल्टीवर्स के दुश्मन पीटर पार्कर की दुनिया में।') WHERE slug='spider-man-no-way-home';
UPDATE movies SET overview = CONCAT(overview,'\n\n','टूटती हकीकतों के बीच डॉक्टर स्ट्रेंज को एक शक्तिशाली यात्री की रक्षा करनी है, जबकि एक जाना-पहचाना साथी ग़म और ताकत में डूब जाता है।'), short_description = CONCAT(short_description,' | ','स्ट्रेंज मल्टीवर्स के खतरों से जूझता है।') WHERE slug='doctor-strange-in-the-multiverse-of-madness';
UPDATE movies SET overview = CONCAT(overview,'\n\n','शांति की तलाश में लगे थॉर की ज़िंदगी तब उलट जाती है जब देवताओं का सफ़ाया करने निकला एक खलनायक सामने आता है और उसकी पुरानी प्रेमिका नई ताकत के साथ लौटती है।'), short_description = CONCAT(short_description,' | ','थॉर देवताओं के शिकारी से भिड़ता है।') WHERE slug='thor-love-and-thunder';
UPDATE movies SET overview = CONCAT(overview,'\n\n','एक गहरे दुख से जूझता वकांडा अपने देश को ज़मीन और समंदर से उठते नए खतरों से बचाने के लिए नई राह तलाशता है।'), short_description = CONCAT(short_description,' | ','वकांडा अपने देश की रक्षा करता है।') WHERE slug='black-panther-wakanda-forever';
UPDATE movies SET overview = CONCAT(overview,'\n\n','स्कॉट लैंग और उसका परिवार एक रहस्यमयी और खतरनाक सूक्ष्म दुनिया में फँस जाते हैं, जहाँ उनका सामना एक ताकतवर विजेता कांग से होता है।'), short_description = CONCAT(short_description,' | ','एंट-मैन का परिवार क्वांटम दुनिया में फँसता है।') WHERE slug='ant-man-and-the-wasp-quantumania';
UPDATE movies SET overview = CONCAT(overview,'\n\n','जब उनका एक साथी खतरे में पड़ता है, तो गार्डियंस उसे बचाने के एक जोखिम भरे मिशन पर निकलते हैं और उसके दर्दनाक अतीत से रूबरू होते हैं।'), short_description = CONCAT(short_description,' | ','गार्डियंस अपने साथी को बचाने निकलते हैं।') WHERE slug='guardians-of-the-galaxy-vol-3';
UPDATE movies SET overview = CONCAT(overview,'\n\n','तीन नायिकाओं की शक्तियाँ रहस्यमयी ढंग से आपस में उलझ जाती हैं, और उन्हें एक बदला लेने वाले खतरे को रोकने के लिए साथ मिलकर काम करना पड़ता है।'), short_description = CONCAT(short_description,' | ','तीन नायिकाएँ मिलकर एक खतरे से लड़ती हैं।') WHERE slug='the-marvels';
UPDATE movies SET overview = CONCAT(overview,'\n\n','बेलगाम और बदज़ुबान भाड़े का सिपाही डेडपूल एक थके-हारे म्यूटेंट वॉल्वरिन को एक पागलपन भरे मिशन में घसीट लेता है। ज़बरदस्त एक्शन और बेतहाशा कॉमेडी।'), short_description = CONCAT(short_description,' | ','डेडपूल और वॉल्वरिन की धमाकेदार जोड़ी।') WHERE slug='deadpool-and-wolverine';
UPDATE movies SET overview = CONCAT(overview,'\n\n','नए कैप्टन अमेरिका बने सैम विल्सन एक अंतरराष्ट्रीय साज़िश के बीच फँस जाते हैं जो एक वैश्विक संकट खड़ा कर सकती है, और उन्हें सच्चाई का पर्दाफ़ाश करना है।'), short_description = CONCAT(short_description,' | ','सैम विल्सन एक बड़ी साज़िश से भिड़ता है।') WHERE slug='captain-america-brave-new-world';
UPDATE movies SET overview = CONCAT(overview,'\n\n','खलनायकों और बागियों की एक टोली को एक ऐसे मिशन पर भेजा जाता है जो उन्हें खत्म करने के लिए रचा गया है, और उन्हें मिलकर मुक्ति का एक मौका मिलता है।'), short_description = CONCAT(short_description,' | ','एंटी-हीरो की टोली को मुक्ति का मौका।') WHERE slug='thunderbolts';
UPDATE movies SET overview = CONCAT(overview,'\n\n','अंतरिक्ष यात्रा के बाद असाधारण शक्तियाँ पाने वाले खोजकर्ताओं का एक परिवार एक विशाल ब्रह्मांडीय खतरे का सामना करता है। उम्मीद और रोमांच से भरी कहानी।'), short_description = CONCAT(short_description,' | ','चार नायकों का परिवार ब्रह्मांडीय खतरे से भिड़ता है।') WHERE slug='the-fantastic-four-first-steps';
